# Generated by Django 4.0 on 2024-03-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('TENGE', '₸'), ('DOLLAR', '$'), ('RUBL', '₽')], default='TENGE', max_length=6),
        ),
    ]
