# Generated by Django 5.0.4 on 2024-04-24 17:54

import geoposition.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_date_of_birth_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=geoposition.fields.GeopositionField(default='43.23269713756249,76.91163003444672', max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
